// Assignment Code
var generateBtn = document.querySelector("#generate");


// Tries to build with ASCII keys 
// var ASCII_UPPERCASE_ALPHA_START = 65;
// var ASCII_UPPERCASE_ALPHA_END = 90;

// String.fromCharCode(ASCII_UPPERCASE_START) = "A"
// String.fromCharCode(ASCII_UPPERCASE_END) = "Z"

function generatePassword(){

  //seeing if the buton is even pressed 
  console.log("Button has been pressed");

//the possbile criteria for the password type
  var upperArr = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  var lowerArr = "abcdefghijklmnopqrstuvwxyz";
  var numArr  = "0123456789";
  var specArr = '!@#$%^&*()? ';

  var pass = [];
  

// Prompt the user the password settings
var passLength = prompt("choose a length of at least 8 characters and no more than 128 characters");


// checks to see if the user correctly chose a number between 8 and 128
  while(passLength <= 7 || passLength > 129){
    passLength = prompt("choose a length of at least 8 characters and no more than 128 characters")
  }

  // console.log(passLength);
  var lowerCase = confirm("Would you like to use lowercase letters?");
  var upperCase = confirm("Would you like to use capital letters?");
  var numeric = confirm("Would you like any numbers?");
  var specialCharacters = confirm("Would you like special characters?");



  // if the amount of characters is correct along with the criteria the user selected in the confirmed notifications pop up
  // the generated password gets added to the criteria/array/ floor rounds to number/ random choses our numbers.
  for (var i = 0; i < passLength;){
    if(lowerCase){
      pass+=lowerArr[Math.floor(Math.random() * lowerArr.length)]
      i++
      } 
    if(upperCase){
      pass+=upperArr[Math.floor(Math.random() * upperArr.length)]
      i++
      } 
    if(numeric){
      pass+= numArr[Math.floor(Math.random() * numArr.length)]
      i++
      } 
    if(specialCharacters){
      pass+= specArr[Math.floor(Math.random() * specArr.length)]
      i++
      }    
  }

// returns the value of pass which is the password generated by the function 
// returns "pass words will end up here";
  return pass;
}



// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;

}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
